### ISSUE TITLE
[Feature] CLI support

### ISSUE THREAD

**Issue by nopeless** [seerge/g14-helper#1]
Will the project support cli mode and JSON like stats?

ex)
```sh
> g14-helper status -f json
{
  "refresh_rate": 120,
  "mode": "eco"
}
> g14-helper set refresh_rate 65
Err: valid options are 60, 120
```

I am willing to help on this issue

**Comment by seerge** [comment]
That will be possible in future, I have just added support of JSON config files to the app. Loading custom config via CLI won't be difficult from here.

**Comment by seerge** [comment]
Closing this, as it's not relevant anymore, as app has grown up and not a powershell script :)

**Comment by nopeless** [comment]
I don't think it being a powershell script or not is relevant, but I don't have time to contribute to this repository at the moment so who am I to tell otherwise.

Keep up the good work 👍

**Comment by colemickens** [comment]
This is something I'm still interested in, but also not qualified or able to work on.

Particularly, asusctl in Linux is nice because I have a command that calls asusctl to switch the dGPU, then call efibootmgr to set the `bootnext` efivar, and then reboot.

Similarly, I have a `reboot-linux.bat` that use `bcedit` to set (whatever it calls the bootnext variable), but I currently don't have a good way to flip it back to Integrated without opening GHelper.

It's a super minor request, of course, and GHelper and it's GUI are so clean and nice I feel guilty even asking.
